DATA:
  train_name: coco
  test_name: default
  data_root: /coco
  train_split: 0
  test_split: default
  train_list: lists/coco/train.txt
  val_list: lists/coco/val.txt
  num_classes_tr: 
  num_classes_val: 
  use_split_coco: True
  workers: 2
  image_size: 473
  padding_label: 255
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  scale_min: 0.5
  scale_max: 2.0
  rot_min: -10
  rot_max: 10
  padding: avg
  augmentations: ['resize']

TRAIN:
  resume_weight: pretrained/coco/split0/pspnet_resnet50/best.pth
  batch_size: 1
  epochs: 1
  log_freq: 200
  lr_cls: 0.1         # classifier lr
  lr_meta: 0.0005     # meta model lr
  lr_stepsize: 30
  momentum: 0.9
  gamma: 0.1
  nesterov: True
  weight_decay: 0.0001
  main_optim: SGD
  scheduler: cosine
  milestones: 
  iter_per_epoch: 
  adapt_iter: 100
  per_epoch_val: 30
  miou_grp_size: 4

MODEL:
  arch: pspnet
  backbone: resnet
  layers: 50
  zoom_factor: 8
  pretrained: True
  final_pool: False
  m_scale: False
  use_ppm: True
  rmid: 
  dropout: 0.1
  bins: [1, 2, 3, 6]
  bottleneck_dim: 512
  encoder_blocks: 5
  encoder_dim: 512
  decoder_dim: 
  patch_size: 16
  extra_tokens_num: 0
  decoder: 
  feats_type: cnn
  inner_loss: wce
  meta_loss: wce
  meta_model: sample
  norm_s: False
  norm_q: True
  heads: 4
  att_dropout: 0.5
  loss_idx: 1
  use_amp: True

EVALUATION:
  shot: 1
  random_shot: False
  batch_size_val: 
  manual_seed: 42
  test_num: 1000
  n_runs: 1
  save_flag: True